### ISSUE TITLE
[Bug] App Crash: IllegalArgumentException

### ISSUE THREAD

**Issue by mackiecarr89** [T8RIN/ImageToolbox#1022]
**Describe the bug**
[Bug] App Crash: IllegalArgumentException

Device: SM-G988W (samsung - z3q), SDK: 33 (13), App: 2.8.1 (136)

java.lang.IllegalArgumentException: red = 0.0, green = 0.0, blue = 0.0, alpha = -3.833397E-8 outside the range for sRGB IEC61966-2.1 (id=0, model=Rgb)
	at androidx.compose.ui.graphics.a.F(SourceFile:3)
	at androidx.compose.ui.graphics.a.b(SourceFile:484)
	at r0.v.c(SourceFile:17)
	at t0.c.a(SourceFile:23)
	at t0.c.i0(SourceFile:44)
	at I0.J.i0(SourceFile:16)
	at t0.g.j(SourceFile:65)
	at t.r.a(SourceFile:587)
	at t.r.n(SourceFile:54)
	at o0.e.a(SourceFile:3)
	at I0.J.b(SourceFile:50)
	at I0.h0.I0(SourceFile:55)
	at I0.h0.G0(SourceFile:30)
	at I0.D.Y0(SourceFile:6)
	at I0.h0.I0(SourceFile:9)
	at I0.h0.G0(SourceFile:30)
	at androidx.compose.ui.node.a.i(SourceFile:5)
	at I0.y.Y0(SourceFile:28)
	at I0.h0.I0(SourceFile:9)
	at I0.h0.G0(SourceFile:30)
	at I0.D.Y0(SourceFile:6)
	at I0.h0.I0(SourceFile:9)
	at I0.h0.G0(SourceFile:30)
	at androidx.compose.ui.node.a.i(SourceFile:5)
	at I0.y.Y0(SourceFile:28)
	at I0.h0.I0(SourceFile:9)
	at I0.h0.G0(SourceFile:30)
	at androidx.compose.ui.node.a.i(SourceFile:5)
	at I0.y.Y0(SourceFile:28)
	at I0.h0.I0(SourceFile:9)
	at I0.h0.G0(SourceFile:30)
	at I0.D.Y0(SourceFile:6)
	at I0.h0.I0(SourceFile:9)
	at I0.h0.G0(SourceFile:30)
	at androidx.compose.ui.node.a.i(SourceFile:5)
	at I0.y.Y0(SourceFile:28)
	at I0.h0.I0(SourceFile:9)
	at t.Y.b(SourceFile:257)
	at t.Y.d(SourceFile:166)
	at F3.Z4.e(SourceFile:114)
	at i0.w.a(SourceFile:52)
	at i0.x.c(SourceFile:140)
	at I0.u0.a(SourceFile:3)
	at Y.L0.n(SourceFile:416)
	at J0.X0.A(SourceFile:22)
	at J0.a1.i(SourceFile:40)
	at J0.a1.l(SourceFile:14)
	at I0.h0.G0(SourceFile:5)
	at androidx.compose.ui.node.a.i(SourceFile:5)
	at I0.y.Y0(SourceFile:28)
	at I0.h0.I0(SourceFile:9)
	at I0.h0.G0(SourceFile:30)
	at androidx.compose.ui.node.a.i(SourceFile:5)
	at J0.z.dispatchDraw(SourceFile:69)
	at android.view.View.draw(View.java:24409)
	at android.view.View.updateDisplayListIfDirty(View.java:23267)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4732)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4704)
	at android.view.View.updateDisplayListIfDirty(View.java:23214)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4732)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4704)
	at android.view.View.updateDisplayListIfDirty(View.java:23214)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:777)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:783)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:881)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:5647)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:5330)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4486)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3116)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10885)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1301)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1309)
	at android.view.Choreographer.doCallbacks(Choreographer.java:923)
	at android.view.Choreographer.doFrame(Choreographer.java:852)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1283)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

**To Reproduce**

When previewing full filters intermittently and doesn't seem to be one specific filter as the cause. I've tried it many times and the filter which caused it to crash previously ends up working when I try again but then it crashes after selecting a different filter.

**Comment by T8RIN** [comment]
Should be fixed by bumping compose to 1.7.0-alpha08 in 2.8.2-alpha01
