### ISSUE TITLE
[Bug] App Crash: NullPointerException

### ISSUE THREAD

**Issue by iTzOkimARMENIAN** [T8RIN/ImageToolbox#1096]
Device: SM-A546U (samsung - a54x), SDK: 34 (14), App: 2.8.2-alpha02 (138)java.lang.NullPointerException: Attempt to read from field 'N0.O N0.G.M' on a null object reference in method 'void N0.G.J(N0.G)'at N0.G.J(SourceFile:1)at N0.G.P(SourceFile:20)at N0.y0.h(SourceFile:5)at d0.y.a(SourceFile:11)at d0.J.W(SourceFile:26)at d0.a.U(SourceFile:3)at c0.u.j(SourceFile:51)at c0.u.i(SourceFile:6)at c0.v0.n(SourceFile:174)at O0.b0.doFrame(SourceFile:34)at O0.Z.doFrame(SourceFile:48)at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1648)at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1659)at android.view.Choreographer.doCallbacks(Choreographer.java:1129)at android.view.Choreographer.doFrame(Choreographer.java:1045)at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1622)at android.os.Handler.handleCallback(Handler.java:958)at android.os.Handler.dispatchMessage(Handler.java:99)at android.os.Looper.loopOnce(Looper.java:230)at android.os.Looper.loop(Looper.java:319)at android.app.ActivityThread.main(ActivityThread.java:8893)at java.lang.reflect.Method.invoke(Native Method)at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)Suppressed: L6.g: [O0.c0@1db0cc7, O0.G0@11342f4, F{Cancelling}@520a1d, a0@1715492]

**Comment by T8RIN** [comment]
Duplicate of #1039
