### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Bizocorp** [T8RIN/ImageToolbox#1214]
[Bug] App Crash: IllegalArgumentException

Device: SM-A536B (samsung - a53x), SDK: 34 (14), App: 2.9.1-alpha01 (145)

java.lang.IllegalArgumentException: MutableState containing Color(0.0, 0.0, 0.0, 0.0, sRGB IEC61966-2.1) cannot be saved using the current SaveableStateRegistry. The default implementation only supports types which can be stored inside the Bundle. Please consider implementing a custom Saver for this class and pass it as a stateSaver parameter to rememberSaveable().
	at N0.a.a(SourceFile:86)
	at N0.a.b(SourceFile:1)
	at E0.v.f(SourceFile:127)
	at E0.w.j(SourceFile:64)
	at E0.w.i(SourceFile:6)
	at E0.H0.a(SourceFile:105)
	at E0.p.a(SourceFile:5)
	at E0.w.o(SourceFile:9)
	at n1.G.i(SourceFile:22)
	at n1.G.h(SourceFile:120)
	at n1.B.m(SourceFile:160)
	at g0.O.a(SourceFile:34)
	at e0.l.b(SourceFile:21)
	at e0.m.l(SourceFile:837)
	at M9.p.l(SourceFile:825)
	at n1.D.c(SourceFile:74)
	at p1.t.c(SourceFile:38)
	at X0.V.f(SourceFile:1)
	at p1.y.c(SourceFile:15)
	at X0.V.f(SourceFile:1)
	at p1.y.c(SourceFile:15)
	at d0.C.f(SourceFile:99)
	at p1.y.c(SourceFile:15)
	at p1.J.b(SourceFile:882)
	at O0.p.e(SourceFile:114)
	at O0.q.a(SourceFile:48)
	at O0.r.c(SourceFile:140)
	at p1.j0.a(SourceFile:3)
	at p1.I.w0(SourceFile:133)
	at p1.D.M(SourceFile:17)
	at p1.D.N(SourceFile:18)
	at p1.Q.c(SourceFile:8)
	at p1.Q.m(SourceFile:138)
	at p1.Q.j(SourceFile:90)
	at q1.t.s(SourceFile:36)
	at q1.t.dispatchDraw(SourceFile:17)
	at android.view.View.draw(View.java:25180)
	at android.view.View.updateDisplayListIfDirty(View.java:24036)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4764)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4736)
	at android.view.View.updateDisplayListIfDirty(View.java:23982)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4764)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4736)
	at android.view.View.updateDisplayListIfDirty(View.java:23982)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4764)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4736)
	at android.view.View.updateDisplayListIfDirty(View.java:23982)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4764)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4736)
	at android.view.View.updateDisplayListIfDirty(View.java:23982)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4764)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4736)
	at android.view.View.updateDisplayListIfDirty(View.java:23982)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4764)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4736)
	at android.view.View.updateDisplayListIfDirty(View.java:23982)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:768)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:774)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:872)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:6051)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:5706)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4795)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3288)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:11344)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1689)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1698)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1153)
	at android.view.Choreographer.doFrame(Choreographer.java:1079)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1646)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

**Comment by TheNewsYorkTime** [comment]
I'm having the same crash. I was opening an image from my downloads using the builtin file picker.


[Bug] App Crash: IllegalArgumentException

Device: moto g power (motorola - sofia), SDK: 30 (11), App: 2.9.1-alpha01 (145)

Log: (Truncated for brevity)
java.lang.IllegalArgumentException: MutableState containing Color(0.0, 0.0, 0.0, 0.0, sRGB IEC61966-2.1) cannot be saved using the current SaveableStateRegistry. The default implementation only supports types which can be stored inside the Bundle. Please consider implementing a custom Saver for this class and pass it as a stateSaver parameter to rememberSaveable().

**Comment by TheNewsYorkTime** [comment]
I tried all the input sources and it seems to be unrelated to that. Only when I try to edit a photo is the crash triggered. I can view photos, it's just editing them that's the problem.

**Comment by T8RIN** [comment]
It's because some color values stored on ui can't be saved anymore, so i know how to fix it, this will be in alpha02

**Comment by T8RIN** [comment]
I'm not at home now, so i will fix it as soon as i can
