### ISSUE TITLE
[Bug] App Crash: OutOfMemoryError

### ISSUE THREAD

**Issue by Toshit1012** [T8RIN/ImageToolbox#1369]
![Screenshot_2024-09-27-12-13-26-670_ru tech imageresizershrinker](https://github.com/user-attachments/assets/2c52dd40-8617-4cf1-a9bd-391c8f005f29)
![Screenshot_2024-09-27-12-13-26-670_ru tech imageresizershrinker](https://github.com/user-attachments/assets/96bc09a3-51e2-4a0f-943e-4a94cf72c34d)
Device: 22021211RI (POCO - munch), SDK: 34 (14), App: 2.9.1-alpha03 (147)java.lang.OutOfMemoryError: Failed to allocate a 249803592 byte allocation with 25165824 free bytes and 231MB until OOM, target footprint 319031560, growth limit 536870912at java.util.Arrays.copyOf(Arrays.java:3585)at java.io.ByteArrayOutputStream.toByteArray(ByteArrayOutputStream.java:211)at ee.c.u(SourceFile:406)at O8.a.q(SourceFile:9)at ua.H.run(SourceFile:95)at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)at java.lang.Thread.run(Thread.java:1012)Suppressed: za.g: [v0{Cancelling}@cd57db7, Dispatchers.Main.immediate]

**Comment by T8RIN** [comment]
use preset below 100, fe 60
