### ISSUE TITLE
[Bug] App Crash on "New Version" Bottom Sheet and "Donation"

### ISSUE THREAD

**Issue by egmsia01** [T8RIN/ImageToolbox#1370]
**Describe the bug**
When the app is launched and the update screen or donation screen pops up, swiping from the edge of the screen to return to the main activity causes the app to crash.

**To Reproduce**
When the app is launched and the update screen or donation screen pops up, swiping from the edge of the screen returns to the main activity.

**Expected behavior**
Should back to home Activity.

**Screenshots**
https://github.com/user-attachments/assets/96b0872f-9053-4d05-8013-fe496201877d

**Smartphone (please complete the following information):**
 - Device: Xiaomi 13
 - OS: Android 14 / Hyper OS 1.0

**Comment by T8RIN** [comment]
maybe internal jetpack compose bug, waiting for updates

**Comment by T8RIN** [comment]
you can disable auto showing update sheet in settings

**Comment by egmsia01** [comment]
### The following is the crash log:

Device: 2211133C (Xiaomi - fuxi), SDK: 34 (14), App: 3.0.0 (152)

java.lang.NullPointerException: Attempt to invoke virtual method 'float android.window.BackMotionEvent.getTouchX()' on a null object reference
	at android.window.WindowOnBackInvokedDispatcher$OnBackInvokedCallbackWrapper.lambda$onBackStarted$1(WindowOnBackInvokedDispatcher.java:353)
	at android.window.WindowOnBackInvokedDispatcher$OnBackInvokedCallbackWrapper.$r8$lambda$jWVwe-YeLRxW3tAMLuWZynG6e1k(Unknown Source:0)
	at android.window.WindowOnBackInvokedDispatcher$OnBackInvokedCallbackWrapper$$ExternalSyntheticLambda4.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8777)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

### My Analysis：
This crash occurred on my Xiaomi 13 (Android 14), but not occur on the Pixel 8 (Android 14).
After I set the `enableOnBackInvokedCallback` to `false`, this problem will disappear, I guess may be related to the properties of the Android 14 "Predictive Back".

**Comment by egmsia01** [comment]
> maybe internal jetpack compose bug, waiting for updates

But...it's not occurred on Pixel 8 (Android 14)，may be the bug come from Hyper OS（╮( •́ω•̀ )╭

**Comment by T8RIN** [comment]
Oh, maybe it is, because on my pixel 8 everything is okay too

**Comment by T8RIN** [comment]
Should i keep it open?

**Comment by egmsia01** [comment]
> Should i keep it open?

plz close it,thank you,this bug may have been caused by Hyper OS.
