### ISSUE TITLE
[Bug] App Crash: ActivityNotFoundException

### ISSUE THREAD

**Issue by OMElon007** [T8RIN/ImageToolbox#1484]
Device: XT2201-2 (motorola - hiphic), SDK: 34 (14), App: 3.1.0-rc02 (157)android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.SENDTO dat=mailto:xxxxx@xx.xx }at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2244)at android.app.Instrumentation.execStartActivity(Instrumentation.java:1878)at android.app.Activity.startActivityForResult(Activity.java:5717)at b.k.startActivityForResult(SourceFile:2)at android.app.Activity.startActivityForResult(Activity.java:5675)at b.k.startActivityForResult(SourceFile:1)at android.app.Activity.startActivity(Activity.java:6177)at android.app.Activity.startActivity(Activity.java:6144)at Kd.a.a(SourceFile:5)at Ec.L.a(SourceFile:126)at androidx.compose.foundation.u.n(SourceFile:13)at d0.J0.y(SourceFile:390)at M8.a.r(SourceFile:9)at wa.z.A(SourceFile:81)at wa.h.p(SourceFile:101)at wa.h.D(SourceFile:33)at wa.h.r(SourceFile:17)at p1.f0.L0(SourceFile:54)at p1.f0.D(SourceFile:32)at b0.a.D(SourceFile:121)at p1.q.e(SourceFile:157)at p1.q.e(SourceFile:136)at p1.q.e(SourceFile:136)at p1.q.e(SourceFile:136)at p1.q.e(SourceFile:136)at p1.g.b(SourceFile:30)at p1.H.a(SourceFile:120)at w1.q.I(SourceFile:81)at w1.q.l(SourceFile:324)at w1.q.dispatchTouchEvent(SourceFile:76)at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3126)at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3126)at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:511)at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1922)at android.app.Activity.dispatchTouchEvent(Activity.java:4505)at i.u.dispatchTouchEvent(SourceFile:3)at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:469)at android.view.View.dispatchPointerEvent(View.java:15967)at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:7353)at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7147)at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6559)at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6616)at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6582)at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6747)at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6590)at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6804)at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6563)at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6616)at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6582)at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6590)at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6563)at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9708)at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9624)at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9585)at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9855)at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:274)at android.os.MessageQueue.nativePollOnce(Native Method)at android.os.MessageQueue.next(MessageQueue.java:342)at android.os.Looper.loopOnce(Looper.java:183)at android.os.Looper.loop(Looper.java:362)at android.app.ActivityThread.main(ActivityThread.java:8448)at java.lang.reflect.Method.invoke(Native Method)at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:992)Suppressed: Ba.e: [w1.H1@6d78531, K0.e@93ed416, r0{Cancelling}@3633197, K0@c224f84]
除此以外，选择裁剪功能并导入图片后，一直卡住在载入中的界面无法进行下一步:(
![Screenshot_20241122-002722](https://github.com/user-attachments/assets/87e9cb7f-d879-42e1-9ee3-176a27612d0b)

**Comment by OMElon007** [comment]
> That's not a bug rather than you didn't have default mail app

In addition, after selecting the crop function and importing the image, the interface that has been stuck in loading cannot proceed to the next step :(

**Comment by T8RIN** [comment]
cropper is separete one
