### ISSUE TITLE
Crash for unkown reasons

### ISSUE THREAD

**Issue by ChildishGiant** [T8RIN/ImageToolbox#1488]
[Bug] App Crash: RuntimeException

Device: Titan Slim (Unihertz - Titan_Slim), SDK: 30 (11), App: 3.0.0 (152)

java.lang.RuntimeException: Canvas: trying to draw too large(192000000bytes) bitmap.
	at android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:280)
	at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:88)
	at X0.c.n(SourceFile:91)
	at Z0.b.j0(SourceFile:34)
	at p1.G.j0(SourceFile:25)
	at Y.t.i(SourceFile:111)
	at c1.a.i(SourceFile:52)
	at c1.b.g(SourceFile:223)
	at d3.l.i(SourceFile:50)
	at c1.b.g(SourceFile:223)
	at d3.s.e(SourceFile:101)
	at p1.G.d(SourceFile:52)
	at p1.Z.E0(SourceFile:55)
	at p1.Z.C0(SourceFile:28)
	at p1.z.W0(SourceFile:6)
	at p1.Z.E0(SourceFile:9)
	at Y.p.a(SourceFile:459)
	at O0.s.e(SourceFile:114)
	at O0.t.a(SourceFile:52)
	at O0.u.c(SourceFile:131)
	at p1.h0.a(SourceFile:3)
	at ad.i.k(SourceFile:1411)
	at p1.a.l(SourceFile:425)
	at a1.g.S(SourceFile:35)
	at a1.b.e(SourceFile:55)
	at q1.q0.i(SourceFile:136)
	at q1.s.dispatchDraw(SourceFile:99)
	at android.view.View.draw(View.java:22602)
	at android.view.View.updateDisplayListIfDirty(View.java:21431)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4632)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4605)
	at android.view.View.updateDisplayListIfDirty(View.java:21381)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4632)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4605)
	at android.view.View.updateDisplayListIfDirty(View.java:21381)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4632)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4605)
	at android.view.View.updateDisplayListIfDirty(View.java:21381)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4632)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4605)
	at android.view.View.updateDisplayListIfDirty(View.java:21381)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4632)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4605)
	at android.view.View.updateDisplayListIfDirty(View.java:21381)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4632)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4605)
	at android.view.View.updateDisplayListIfDirty(View.java:21381)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:559)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:565)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:642)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4234)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3957)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3215)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2028)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8810)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:974)
	at android.view.Choreographer.doCallbacks(Choreographer.java:797)
	at android.view.Choreographer.doFrame(Choreographer.java:732)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:959)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7700)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)

Oh also on the bug report screen the github button only copies the error but doesn't open github.

**Comment by T8RIN** [comment]
There is a reason, that your image is too big, but this should not happen anyways, so you can try the latest release candidate of 3.1.0
