### ISSUE TITLE
[Bug] App Crash: NullPointerException

### ISSUE THREAD

**Issue by DrAnonym666** [T8RIN/ImageToolbox#1543]
Device: 23124RA7EO (Redmi - sapphiren), SDK: 34 (14), App: 3.1.1 (161)

java.lang.NullPointerException: Attempt to read from field 'int android.view.View.mViewFlags' on a null object reference in method 'void android.view.ViewGroup.dispatchDraw(android.graphics.Canvas)'
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4379)
	at android.view.View.draw(View.java:24735)
	at com.android.internal.policy.DecorView.draw(DecorView.java:896)
	at android.view.View.updateDisplayListIfDirty(View.java:23563)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:726)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:735)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:845)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:5622)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:5301)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4425)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2995)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10331)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1594)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1603)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1125)
	at android.view.Choreographer.doFrame(Choreographer.java:1030)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1567)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8763)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

What to Do? Every time after edit picture or save picture this comes. Picture is saved, but its a lol bit Confusing.

Tested with github Version, playstore Version and f-droid... Oh pardon... Telegramm app Tested too. What should i Do?

**Comment by T8RIN** [comment]
could you send export og your settings?

**Comment by T8RIN** [comment]
also which screen exactly causes this?

**Comment by T8RIN** [comment]
Also please try on the latest CI actions build

**Comment by T8RIN** [comment]
https://issuetracker.google.com/issues/390138266

**Comment by T8RIN** [comment]
i think it's fixed withing last jetpack compose alpha
