### ISSUE TITLE
[Bug] App Crash: IllegalArgumentException

### ISSUE THREAD

**Issue by v1s7** [T8RIN/ImageToolbox#1553]
Device: RMX3085 (realme - RMX3085L1), SDK: 33 (13), App: 3.1.1 (161)java.lang.IllegalArgumentException: Invalid ID, must be in the range [0..16)at android.graphics.ColorSpace.get(ColorSpace.java:1390)at android.graphics.Color.colorSpace(Color.java:703)at android.graphics.Paint.setColor(Paint.java:1141)at d1.a.j(SourceFile:1)at d1.u0.b(SourceFile:1)at d1.j.e(SourceFile:11)at f1.a.b(SourceFile:41)at f1.a.g0(SourceFile:78)at v1.N.g0(SourceFile:19)at d1.a0.d(SourceFile:172)at androidx.compose.foundation.f.h(SourceFile:146)at v1.N.c(SourceFile:50)at v1.t0.L0(SourceFile:53)at v1.t0.K0(SourceFile:28)at v1.G.h1(SourceFile:6)at v1.t0.L0(SourceFile:9)at v1.t0.K0(SourceFile:28)at v1.J.j(SourceFile:5)at v1.z.h1(SourceFile:28)at v1.t0.L0(SourceFile:9)at v1.t0.K0(SourceFile:28)at v1.G.h1(SourceFile:6)at v1.t0.L0(SourceFile:9)at v1.t0.K0(SourceFile:28)at v1.J.j(SourceFile:5)at v1.z.h1(SourceFile:28)at v1.t0.L0(SourceFile:9)at v1.t0.K0(SourceFile:28)at v1.G.h1(SourceFile:6)at v1.t0.L0(SourceFile:9)at v1.t0.K0(SourceFile:28)at v1.G.h1(SourceFile:6)at v1.t0.L0(SourceFile:9)at v1.t0.K0(SourceFile:28)at v1.J.j(SourceFile:5)at v1.z.h1(SourceFile:28)at v1.t0.L0(SourceFile:9)at v1.t0.K0(SourceFile:28)at v1.J.j(SourceFile:5)at v1.z.h1(SourceFile:28)at v1.t0.L0(SourceFile:9)at v1.v0.a(SourceFile:10)at U0.j$a.c(SourceFile:114)at U0.C$a.a(SourceFile:58)at U0.C.e(SourceFile:128)at v1.W0.b(SourceFile:3)at v1.u0.l(SourceFile:35)at w1.s1.n(SourceFile:23)at g1.c.n(SourceFile:60)at g1.k.M(SourceFile:37)at g1.f.f(SourceFile:49)at g1.f.e(SourceFile:55)at w1.t1.i(SourceFile:101)at w1.q.dispatchDraw(SourceFile:69)at android.view.View.draw(View.java:23469)at android.view.View.updateDisplayListIfDirty(View.java:22297)at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4595)at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4568)at android.view.View.updateDisplayListIfDirty(View.java:22248)at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4595)at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4568)at android.view.View.updateDisplayListIfDirty(View.java:22248)at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4595)at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4568)at android.view.View.updateDisplayListIfDirty(View.java:22248)at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4595)at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4568)at android.view.View.updateDisplayListIfDirty(View.java:22248)at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4595)at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4568)at android.view.View.updateDisplayListIfDirty(View.java:22248)at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4595)at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4568)at android.view.View.updateDisplayListIfDirty(View.java:22248)at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:682)at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:688)at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:790)at android.view.ViewRootImpl.draw(ViewRootImpl.java:4897)at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4588)at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3774)at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2474)at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9482)at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1412)at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1420)at android.view.Choreographer.doCallbacks(Choreographer.java:1047)at android.view.ChoreographerExtImpl.checkScrollOptSceneEnable(ChoreographerExtImpl.java:450)at android.view.Choreographer.doFrame(Choreographer.java:918)at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1395)at android.os.Handler.handleCallback(Handler.java:942)at android.os.Handler.dispatchMessage(Handler.java:99)at android.os.Looper.loopOnce(Looper.java:240)at android.os.Looper.loop(Looper.java:351)at android.app.ActivityThread.main(ActivityThread.java:8370)at java.lang.reflect.Method.invoke(Native Method)at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:568)at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

**Comment by T8RIN** [comment]
https://slack-chats.kotlinlang.org/t/26797364/hello-i-am-getting-the-crash-below-with-the-latest-compose-b

**Comment by T8RIN** [comment]
https://issuetracker.google.com/issues/388055627

fixed
