### ISSUE TITLE
Custom output folder

### ISSUE THREAD

**Issue by alabotski** [T8RIN/ImageToolbox#289]
Google Pixel 7 Pro
Android 13

```
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT_TREE flg=0x43 }
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT_TREE flg=0x43 }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2200)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1839)
	at android.app.Activity.startActivityForResult(Activity.java:5506)
	at androidx.activity.n.startActivityForResult(SourceFile:2)
	at q2.a.b(Unknown Source:0)
	at androidx.activity.i.b(SourceFile:158)
	at androidx.activity.result.d.c1(Unknown Source:25)
	at b.a.a(Unknown Source:4)
	at r8.t.a(SourceFile:66)
	at r8.t.l(SourceFile:43)
	at o.w.j0(SourceFile:292)
	at r.s2.j(SourceFile:134)
	at k6.a.n(Unknown Source:8)
	at r6.i.r1(Unknown Source:80)
	at c7.g.t(SourceFile:138)
	at c7.g.F(SourceFile:45)
	at c7.g.n(SourceFile:17)
	at o1.p0.D0(SourceFile:51)
	at o1.p0.Q(Unknown Source:30)
	at q.d.Q(SourceFile:9)
	at o1.h.e(SourceFile:181)
	at o1.h.e(SourceFile:160)
	at o1.h.e(SourceFile:160)
	at o1.h.e(SourceFile:160)
	at o1.h.e(SourceFile:160)
	at o1.h.e(SourceFile:160)
	at o1.h.e(SourceFile:160)
	at o1.h.e(SourceFile:160)
	at o1.i.e(SourceFile:26)
	at k.a0.d(SourceFile:29)
	at l0.y.i(SourceFile:191)
	at androidx.compose.ui.platform.AndroidComposeView.I(SourceFile:79)
	at androidx.compose.ui.platform.AndroidComposeView.o(SourceFile:224)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchTouchEvent(SourceFile:88)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:500)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1905)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4298)
	at f.d0.f(Unknown Source:2)
	at f.d0.dispatchTouchEvent(Unknown Source:0)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:458)
	at android.view.View.dispatchPointerEvent(View.java:15269)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6757)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6557)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6013)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6070)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6036)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6201)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6044)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6258)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6017)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6070)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6036)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6044)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6017)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9103)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9054)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9023)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9226)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:267)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loopOnce(Looper.java:161)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7884)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
	Suppressed: h7.e: [androidx.compose.ui.platform.u1@95d81d7, o0.f@da9fac4, m1{Cancelling}@35fadad, u0@775d8e2]
```

(https://github.com/T8RIN/ImageToolbox/assets/439337/9e990f3c-4207-4636-a701-716d972b54f2)
(https://github.com/T8RIN/ImageToolbox/assets/439337/5d4c9cef-8b67-4c8d-b82d-3080f1c30907)

**Comment by T8RIN** [comment]
Did you have gms?

**Comment by alabotski** [comment]
I have root and delete some app

![Screenshot_20230611-034542.png](https://github.com/T8RIN/ImageToolbox/assets/439337/194f6a53-b751-47ac-abb9-76cc9aebc3e4)

**Comment by T8RIN** [comment]
Reactivate files by google, it can't work without that :(

**Comment by T8RIN** [comment]
I will add toast to inform users if they disabled that

**Comment by T8RIN** [comment]
Can you tell then please, which application is needed to activate, i think it is the "files" only

**Comment by alabotski** [comment]
Yes after reactive all app
newpipe 
vaadin
seal

and you

start work well

**Comment by T8RIN** [comment]
Great!
