### ISSUE TITLE
[Crash, reproducible]: Resize type Ratio

### ISSUE THREAD

**Issue by Runner86** [T8RIN/ImageToolbox#292]
Version: 2.1.3 on Android 12
Feature: Batch resize

Use case:
- Import 2 or more Images
- set Resize type to Ratio
- Enter new value at data field Height

Observed result (1):
The display for Height shows other values then typed.

Observed result (2):
Trying to correct the values for Height will crash the app, see log below.

java.lang.OutOfMemoryError
java.lang.OutOfMemoryError
	at android.graphics.Bitmap.nativeCreate(Native Method)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:1104)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:934)
	at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:789)
	at q9.r.t(SourceFile:135)
	at q9.j.j(SourceFile:89)
	at q9.j.a0(SourceFile:13)
	at j5.e.F1(SourceFile:5)
	at j5.e.S1(SourceFile:74)
	at q9.r.s(SourceFile:27)
	at g8.g.j(SourceFile:68)
	at k6.a.n(Unknown Source:8)
	at c7.c0.run(Unknown Source:109)
	at k.j.run(SourceFile:253)
	at i7.i.run(Unknown Source:2)
	at i7.a.run(SourceFile:94)
	Suppressed: h7.e: [m1{Cancelling}@dc43d24, Dispatchers.Main.immediate]

**Comment by T8RIN** [comment]
You're trying to make it too large to be displayed on your device

**Comment by Runner86** [comment]
Oh yes, that's due to the root cause described as "Observed results (1)" - the Height input value can't be edited correctly in this case (as it is for the Width value). To be more precise: the original value at the input field can't be deleted or overwritten. For example: if one or more digits are deleted with the backspace key, the original value pops up again. Only if a Preset is choosen, the Width and Height fields are updated. Adding additional digits to this entry will crash the app. 
On the other hand side: if there are limits for input values, its better to let the app care for it. Or the input fields has to be locked for user input if it is the intended use case that valid inputs are only allowed from the Presets.

**Comment by T8RIN** [comment]
Fixed

**Comment by T8RIN** [comment]
Wait for the 2.2
