### ISSUE TITLE
NullPointerException during startup

### ISSUE THREAD

**Issue by Jesse205** [T8RIN/ImageToolbox#379]
Version：2.2.2 beta02
System：HarmonyOS 3，Android 10

I tried to clear the data, but it didn't work.
```
NullPointerException

java.lang.NullPointerException
	at com.t8rin.dynamic.theme.b.a(SourceFile:90)
	at com.t8rin.dynamic.theme.b.m(SourceFile:190)
	at sa.d.R(SourceFile:76)
	at j0.a.j(SourceFile:293)
	at j0.a.e(SourceFile:216)
	at j0.d.e0(SourceFile:878)
	at m9.b.U(SourceFile:413)
	at w0.c.d(SourceFile:46)
	at w0.c.U(SourceFile:1)
	at x.b0.a(SourceFile:238)
	at x.b0.f0(SourceFile:65)
	at w0.c.f0(SourceFile:54)
	at a7.h.l(SourceFile:177)
	at x0.g.f(SourceFile:98)
	at dev.olshevski.navigation.reimagined.s.f(SourceFile:73)
	at dev.olshevski.navigation.reimagined.d0.a(SourceFile:38)
	at dev.olshevski.navigation.reimagined.d0.f0(SourceFile:17)
	at w0.c.f0(SourceFile:54)
	at a7.h.m(SourceFile:164)
	at dev.olshevski.navigation.reimagined.e0.a(SourceFile:132)
	at dev.olshevski.navigation.reimagined.a.U(SourceFile:75)
	at w0.c.d(SourceFile:46)
	at w0.c.U(SourceFile:1)
	at o.l.a(SourceFile:137)
	at o.l.b0(SourceFile:440)
	at w0.c.e(SourceFile:46)
	at w0.c.b0(SourceFile:1)
	at a7.h.a(SourceFile:787)
	at o.m.a(SourceFile:288)
	at o.m.f0(SourceFile:17)
	at w0.c.f0(SourceFile:54)
	at d0.g1.o(SourceFile:1015)
	at dev.olshevski.navigation.reimagined.b.b0(SourceFile:115)
	at a7.h.g(SourceFile:305)
	at e6.b.b(SourceFile:355)
	at e6.b.a(SourceFile:550)
	at j0.d.n0(SourceFile:177)
	at ja.g.a(SourceFile:40)
	at ja.g.f0(SourceFile:17)
	at w0.c.f0(SourceFile:54)
	at r.k0.F(SourceFile:5)
	at g0.n2.a(SourceFile:387)
	at g0.n2.f0(SourceFile:29)
	at w0.c.f0(SourceFile:54)
	at a7.h.m(SourceFile:164)
	at androidx.compose.material3.a7.a(SourceFile:142)
	at f9.o.b(SourceFile:132)
	at f9.o.f0(SourceFile:17)
	at w0.c.f0(SourceFile:54)
	at a7.h.l(SourceFile:177)
	at androidx.compose.material3.i9.a(SourceFile:78)
	at q.x.a(SourceFile:516)
	at q.x.f0(SourceFile:198)
	at w0.c.f0(SourceFile:54)
	at a7.h.m(SourceFile:164)
	at a7.h.x(SourceFile:986)
	at x.l0.a(SourceFile:1314)
	at x.l0.f0(SourceFile:78)
	at w0.c.f0(SourceFile:54)
	at a7.h.m(SourceFile:164)
	at com.t8rin.dynamic.theme.j.b(SourceFile:791)
	at j0.c.t(SourceFile:291)
	at ja.g.a(SourceFile:270)
	at ja.g.f0(SourceFile:29)
	at w0.c.f0(SourceFile:54)
	at a7.h.m(SourceFile:164)
	at ja.j.f0(SourceFile:152)
	at w0.c.f0(SourceFile:54)
	at a7.h.l(SourceFile:177)
	at mb.c.a(SourceFile:534)
	at r.l0.b(SourceFile:2413)
	at r.l0.f0(SourceFile:459)
	at w0.c.f0(SourceFile:54)
	at androidx.compose.ui.platform.h1.a(SourceFile:25)
	at o.j.a(SourceFile:2322)
	at o.j.f0(SourceFile:316)
	at w0.c.f0(SourceFile:54)
	at a7.h.m(SourceFile:164)
	at androidx.compose.ui.platform.j1.a(SourceFile:331)
	at x.l0.a(SourceFile:1367)
	at x.l0.f0(SourceFile:102)
	at w0.c.f0(SourceFile:54)
	at a7.h.m(SourceFile:164)
	at androidx.compose.ui.platform.q0.a(SourceFile:495)
	at androidx.compose.ui.platform.i3.a(SourceFile:34)
	at androidx.compose.ui.platform.i3.f0(SourceFile:17)
	at w0.c.f0(SourceFile:54)
	at a7.h.l(SourceFile:177)
	at androidx.compose.ui.platform.i3.a(SourceFile:175)
	at androidx.compose.ui.platform.i3.f0(SourceFile:29)
	at w0.c.f0(SourceFile:54)
	at l7.w.v0(SourceFile:1)
	at o0.r.r(SourceFile:127)
	at o0.w.p(SourceFile:30)
	at o0.f2.a(SourceFile:42)
	at o0.w.c(SourceFile:1)
	at androidx.compose.ui.platform.j3.l0(SourceFile:99)
	at androidx.compose.ui.platform.AndroidComposeView.setOnViewTreeOwnersAvailable(SourceFile:1)
	at androidx.compose.ui.platform.WrappedComposition.c(SourceFile:1)
	at androidx.compose.ui.platform.WrappedComposition.f(SourceFile:1)
	at androidx.lifecycle.v.a(SourceFile:23)
	at androidx.lifecycle.w.a(SourceFile:141)
	at androidx.compose.ui.platform.j3.l0(SourceFile:63)
	at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(SourceFile:139)
	at android.view.View.dispatchAttachedToWindow(View.java:20112)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3619)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3626)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3626)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3626)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3626)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3626)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3626)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2618)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2235)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9043)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1280)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1019)
	at android.view.Choreographer.doFrame(Choreographer.java:911)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1248)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8673)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)

```

**Comment by elea11** [comment]
Same on Lineageos 20, Android 13
Pixel 7 (Panther)
Version 2.2.2-beta02

NullPointerException

java.lang.NullPointerException
	at com.t8rin.dynamic.theme.b.a(SourceFile:51)
	at com.t8rin.dynamic.theme.b.m(SourceFile:15)
	at sa.d.R(SourceFile:76)
	at j0.a.j(SourceFile:275)
	at f9.g.b0(SourceFile:124)
	at w0.c.e(SourceFile:46)
	at w0.c.b0(SourceFile:1)
	at j0.a.e(SourceFile:235)
	at j0.d.e0(SourceFile:878)
	at m9.b.U(SourceFile:413)
	at w0.c.d(SourceFile:46)
	at w0.c.U(SourceFile:1)
	at x.b0.a(SourceFile:238)
	at x.b0.f0(SourceFile:65)
	at w0.c.f0(SourceFile:54)
	at a7.h.l(SourceFile:177)
	at x0.g.f(SourceFile:98)
	at dev.olshevski.navigation.reimagined.s.f(SourceFile:73)
	at dev.olshevski.navigation.reimagined.d0.a(SourceFile:38)
	at dev.olshevski.navigation.reimagined.d0.f0(SourceFile:17)
	at w0.c.f0(SourceFile:54)
	at a7.h.m(SourceFile:164)
	at dev.olshevski.navigation.reimagined.e0.a(SourceFile:132)
	at dev.olshevski.navigation.reimagined.a.U(SourceFile:75)
	at w0.c.d(SourceFile:46)
	at w0.c.U(SourceFile:1)
	at o.l.a(SourceFile:137)
	at o.l.b0(SourceFile:440)
	at w0.c.e(SourceFile:46)
	at w0.c.b0(SourceFile:1)
	at a7.h.a(SourceFile:787)
	at o.m.a(SourceFile:288)
	at o.m.f0(SourceFile:17)
	at w0.c.f0(SourceFile:54)
	at d0.g1.o(SourceFile:1015)
	at dev.olshevski.navigation.reimagined.b.b0(SourceFile:115)
	at a7.h.g(SourceFile:305)
	at e6.b.b(SourceFile:355)
	at e6.b.a(SourceFile:550)
	at j0.d.n0(SourceFile:177)
	at ja.g.a(SourceFile:40)
	at ja.g.f0(SourceFile:17)
	at w0.c.f0(SourceFile:54)
	at r.k0.F(SourceFile:5)
	at g0.n2.a(SourceFile:387)
	at g0.n2.f0(SourceFile:29)
	at w0.c.f0(SourceFile:54)
	at a7.h.m(SourceFile:164)
	at androidx.compose.material3.a7.a(SourceFile:142)
	at f9.o.b(SourceFile:132)
	at f9.o.f0(SourceFile:17)
	at w0.c.f0(SourceFile:54)
	at a7.h.l(SourceFile:177)
	at androidx.compose.material3.i9.a(SourceFile:78)
	at q.x.a(SourceFile:516)
	at q.x.f0(SourceFile:198)
	at w0.c.f0(SourceFile:54)
	at a7.h.m(SourceFile:164)
	at a7.h.x(SourceFile:986)
	at x.l0.a(SourceFile:1314)
	at x.l0.f0(SourceFile:78)
	at w0.c.f0(SourceFile:54)
	at a7.h.m(SourceFile:164)
	at com.t8rin.dynamic.theme.j.b(SourceFile:791)
	at j0.c.t(SourceFile:291)
	at ja.g.a(SourceFile:270)
	at ja.g.f0(SourceFile:29)
	at w0.c.f0(SourceFile:54)
	at a7.h.m(SourceFile:164)
	at ja.j.f0(SourceFile:152)
	at w0.c.f0(SourceFile:54)
	at a7.h.l(SourceFile:177)
	at mb.c.a(SourceFile:534)
	at r.l0.b(SourceFile:2413)
	at r.l0.f0(SourceFile:459)
	at w0.c.f0(SourceFile:54)
	at androidx.compose.ui.platform.h1.a(SourceFile:25)
	at o.j.a(SourceFile:2322)
	at o.j.f0(SourceFile:316)
	at w0.c.f0(SourceFile:54)
	at a7.h.m(SourceFile:164)
	at androidx.compose.ui.platform.j1.a(SourceFile:331)
	at x.l0.a(SourceFile:1367)
	at x.l0.f0(SourceFile:102)
	at w0.c.f0(SourceFile:54)
	at a7.h.m(SourceFile:164)
	at androidx.compose.ui.platform.q0.a(SourceFile:495)
	at androidx.compose.ui.platform.i3.a(SourceFile:34)
	at androidx.compose.ui.platform.i3.f0(SourceFile:17)
	at w0.c.f0(SourceFile:54)
	at a7.h.l(SourceFile:177)
	at androidx.compose.ui.platform.i3.a(SourceFile:175)
	at androidx.compose.ui.platform.i3.f0(SourceFile:29)
	at w0.c.f0(SourceFile:54)
	at l7.w.v0(SourceFile:1)
	at o0.r.r(SourceFile:127)
	at o0.w.p(SourceFile:30)
	at o0.f2.a(SourceFile:42)
	at o0.w.c(SourceFile:1)
	at androidx.compose.ui.platform.j3.l0(SourceFile:99)
	at androidx.compose.ui.platform.AndroidComposeView.setOnViewTreeOwnersAvailable(SourceFile:1)
	at androidx.compose.ui.platform.WrappedComposition.c(SourceFile:1)
	at androidx.compose.ui.platform.WrappedComposition.f(SourceFile:1)
	at androidx.lifecycle.v.a(SourceFile:23)
	at androidx.lifecycle.w.a(SourceFile:141)
	at androidx.compose.ui.platform.j3.l0(SourceFile:63)
	at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(SourceFile:139)
	at android.view.View.dispatchAttachedToWindow(View.java:21357)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3491)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2900)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2371)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9297)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
	at android.view.Choreographer.doFrame(Choreographer.java:832)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7918)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

**Comment by T8RIN** [comment]
Lul, i got the same 🐸

**Comment by T8RIN** [comment]
Lul, I got the same Я заметил проблему, подождите

**Comment by T8RIN** [comment]
I spotted the issue, wait

**Comment by T8RIN** [comment]
Fixed, check new beta
