### ISSUE TITLE
Error on the home screen

### ISSUE THREAD

**Issue by BehemothXxx** [T8RIN/ImageToolbox#387]
This error appears if you click on any section on the main screen, such as Single change or parquet. Android 6

UnsatisfiedLinkError

java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__write_chk" referenced by "/data/app/ru.tech.imageresizershrinker-1/split_config.arm64_v8a.apk"...
	at java.lang.Runtime.loadLibrary(Runtime.java:372)
	at java.lang.System.loadLibrary(System.java:1076)
	at com.radzivon.bartoshyk.avif.coder.HeifCoder.<clinit>(SourceFile)
	at l8.p.<init>(SourceFile:6)
	at ma.e.get(SourceFile:170)
	at g6.a.get(SourceFile:14)
	at ma.g.get(SourceFile:30)
	at d6.c.b(SourceFile:236)
	at d6.f.b(SourceFile)
	at dagger.hilt.android.internal.managers.c.b(SourceFile:35)
	at f.c.g(SourceFile:73)
	at f.c.f(SourceFile)
	at d0.g1.Z1(SourceFile:44)
	at d0.g1.b0(SourceFile:61)
	at ha.l1.T(SourceFile:439)
	at w0.d.d(SourceFile:51)
	at w0.d.T(SourceFile)
	at x.w.a(SourceFile:209)
	at x.w.e0(SourceFile:53)
	at w0.d.e0(SourceFile:59)
	at j0.a.b(SourceFile:181)
	at x0.i.a(SourceFile:115)
	at dev.olshevski.navigation.reimagined.s.f(SourceFile:73)
	at dev.olshevski.navigation.reimagined.c0.a(SourceFile:38)
	at dev.olshevski.navigation.reimagined.c0.e0(SourceFile:17)
	at w0.d.e0(SourceFile:59)
	at j0.a.b(SourceFile:181)
	at dev.olshevski.navigation.reimagined.d0.a(SourceFile:132)
	at dev.olshevski.navigation.reimagined.a.T(SourceFile:75)
	at w0.d.d(SourceFile:51)
	at w0.d.T(SourceFile)
	at o.k.b0(SourceFile:533)
	at w0.d.e(SourceFile:51)
	at w0.d.b0(SourceFile)
	at z6.g.a(SourceFile:692)
	at z6.g.k(SourceFile:291)
	at o.l.a(SourceFile:292)
	at o.l.e0(SourceFile:29)
	at w0.d.e0(SourceFile:59)
	at d0.g1.n(SourceFile:1035)
	at dev.olshevski.navigation.reimagined.b.b0(SourceFile:115)
	at p5.m.b(SourceFile:305)
	at x.w.a(SourceFile:87)
	at x.w.e0(SourceFile:41)
	at o0.p.K(SourceFile:285)
	at o0.p.S(SourceFile:34)
	at pa.c.h(SourceFile:233)
	at pa.c.a(SourceFile:548)
	at o.e.a(SourceFile:49)
	at o.e.e0(SourceFile:17)
	at o0.p.K(SourceFile:285)
	at o0.p.Q(SourceFile:58)
	at o0.p.q(SourceFile:163)
	at o0.p.J(SourceFile:36)
	at o0.u.x(SourceFile:19)
	at o0.z1.q(SourceFile:113)
	at o0.w1.l0(SourceFile:396)
	at androidx.compose.ui.platform.x0.doFrame(SourceFile)
	at androidx.compose.ui.platform.v0.doFrame(SourceFile:48)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:896)
	at android.view.Choreographer.doCallbacks(Choreographer.java:699)
	at android.view.Choreographer.doFrame(Choreographer.java:631)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:884)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:6020)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:936)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:797)
	Suppressed: p7.e: [o0.f1@6ac04ad, androidx.compose.ui.platform.w1@b78e3e2, n1{Cancelling}@ab41373, w0@a8b8230]

**Comment by T8RIN** [comment]
Попробуйте скачать из релизов armeabi-v7 если не поможет, то видимо тут уже как бы все, телефон пора менять, хотя по идее такого быть не должно, потому что я предусмотрел, но попробуйте сначала

**Comment by T8RIN** [comment]
Исправил
