### ISSUE TITLE
Crash when sharing after removing background

### ISSUE THREAD

**Issue by Jesse205** [T8RIN/ImageToolbox#404]
[Bug] App Crash: IllegalStateException
```
Device: HLK-AL00 (HONOR - HWHLK-H), SDK: 29 (10, App: 2.3.0-rc01 (83)

java.lang.IllegalStateException: Offset is unspecified
	at d1.c.e(SourceFile:1)
	at xb.c.Z(SourceFile:603)
	at v0.c.e(SourceFile:46)
	at p.x.a(SourceFile:384)
	at p.x.b0(SourceFile:138)
	at n0.q.L(SourceFile:282)
	at n0.q.R(SourceFile:58)
	at n0.q.r(SourceFile:163)
	at n0.q.J(SourceFile:31)
	at n0.v.y(SourceFile:22)
	at n0.e2.s(SourceFile:112)
	at n0.b2.l0(SourceFile:410)
	at androidx.compose.ui.platform.y0.doFrame(Unknown Source:6)
	at androidx.compose.ui.platform.w0.doFrame(SourceFile:48)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1278)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1019)
	at android.view.Choreographer.doFrame(Choreographer.java:907)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1248)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8673)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
	Suppressed: v9.e: [n0.j1@1e15f0, androidx.compose.ui.platform.w1@f1ea769, n1{Cancelling}@b4575ee, x0@a95ea8f]
```

**Comment by T8RIN** [comment]
Can you record it please?

**Comment by Jesse205** [comment]
Oh no, I can't reproduce it now. Just now there was a second time, but not when sharing, but when selecting a image.

**Comment by T8RIN** [comment]
Sounds interesting, i will check
