### ISSUE TITLE
Software crashes when adjusting brush softness to 0

### ISSUE THREAD

**Issue by Jesse205** [T8RIN/ImageToolbox#543]
function: Sketchpad
background: Pure white
Other options are default
```
[Bug] App Crash: IllegalStateException

Device: HLK-AL00 (HONOR - HWHLK-H), SDK: 29 (10), App: 2.4.3-alpha01 (98)

java.lang.IllegalStateException: Offset is unspecified
	at j1.c.d(SourceFile:1)
	at va.j.o(SourceFile:1072)
	at a1.c.i(SourceFile:46)
	at r.x.a(SourceFile:1187)
	at r.x.p(SourceFile:150)
	at s0.p.K(SourceFile:282)
	at s0.p.Q(SourceFile:58)
	at s0.p.q(SourceFile:156)
	at s0.p.I(SourceFile:28)
	at s0.v.z(SourceFile:21)
	at s0.e2.t(SourceFile:112)
	at s0.b2.r(SourceFile:396)
	at androidx.compose.ui.platform.b1.doFrame(Unknown Source:6)
	at androidx.compose.ui.platform.z0.doFrame(SourceFile:48)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1278)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1019)
	at android.view.Choreographer.doFrame(Choreographer.java:907)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1248)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8673)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
	Suppressed: o8.e: [s0.j1@62f8180, androidx.compose.ui.platform.a2@4af53b9, m1{Cancelling}@43f33fe, a1@534b75f]

```

**Comment by T8RIN** [comment]
Can you please provide a video?

**Comment by Jesse205** [comment]
https://github.com/T8RIN/ImageToolbox/assets/51242302/0a4acc99-aa53-41f5-8456-d13c566b19cb

**Comment by T8RIN** [comment]
Hmm

**Comment by T8RIN** [comment]
Looks like drawer don't know where to draw, that's interesting

**Comment by T8RIN** [comment]
I can’t repeat it myself at all :(

**Comment by T8RIN** [comment]
Maybe fixed
