### ISSUE TITLE
[Bug] App Crash: IllegalArgumentException

### ISSUE THREAD

**Issue by SubOptimal** [T8RIN/ImageToolbox#546]
What I did before
- played around with the "remove background" feature
- I used some of the possible actions, including to revert them, before trying another one
- at the end I decided to go back to the main activity, with not applying any of the changes

```
Device: SM-G973F (samsung - beyond1), SDK: 31 (12), App: 2.4.3-alpha01 (98)
java.lang.IllegalArgumentException: width(-63) must be >= 0
at l2.p.z(SourceFile:31)
at z.r.a(SourceFile:69)
at m0.c.S0(SourceFile:18)
at z.t.p(SourceFile:499)
at s.v0.p(SourceFile:359)
at x1.f0.d(SourceFile:74)
at z1.p.a(SourceFile:51)
at r.m.i(SourceFile:44)
at r.m.o(SourceFile:476)
at x1.z.h(SourceFile:8)
at z1.p.a(SourceFile:83)
at r.m.i(SourceFile:10)
at r.m.o(SourceFile:489)
at x1.z.h(SourceFile:8)
at z1.p.a(SourceFile:83)
at k1.q0.h(SourceFile:1)
at z1.p.a(SourceFile:83)
at v.f0.h(SourceFile:99)
at z1.p.a(SourceFile:83)
at z1.f0.c(SourceFile:26)
at l2.p.K(SourceFile:59)
at c1.y.b(SourceFile:48)
at c1.z.c(SourceFile:162)
at z1.i1.a(SourceFile:1)
at z1.d0.o0(SourceFile:139)
at z1.d0.a(SourceFile:119)
at v.g1.a(SourceFile:394)
at v.e1.d(SourceFile:32)
at z1.p.a(SourceFile:51)
at z1.f0.c(SourceFile:26)
at l2.p.K(SourceFile:59)
at c1.y.b(SourceFile:48)
at c1.z.c(SourceFile:162)
at z1.i1.a(SourceFile:1)
at z1.d0.o0(SourceFile:139)
at z1.d0.a(SourceFile:119)
at v.g1.a(SourceFile:394)
at v.e1.d(SourceFile:32)
at z1.p.a(SourceFile:51)
at v.f0.h(SourceFile:99)
at z1.p.a(SourceFile:83)
at z1.f0.c(SourceFile:26)
at l2.p.K(SourceFile:59)
at c1.y.b(SourceFile:48)
at c1.z.c(SourceFile:162)
at z1.i1.a(SourceFile:1)
at z1.d0.o0(SourceFile:139)
at z1.d0.a(SourceFile:119)
at v.t.d(SourceFile:83)
at z1.p.a(SourceFile:51)
at z1.f0.c(SourceFile:26)
at l2.p.K(SourceFile:59)
at c1.y.b(SourceFile:48)
at c1.z.c(SourceFile:162)
at z1.i1.a(SourceFile:1)
at z1.d0.o0(SourceFile:139)
at z1.d0.a(SourceFile:119)
at v.t.d(SourceFile:83)
at z1.p.a(SourceFile:51)
at z1.f0.c(SourceFile:26)
at l2.p.K(SourceFile:59)
at c1.y.b(SourceFile:48)
at c1.z.c(SourceFile:162)
at z1.i1.a(SourceFile:1)
at z1.d0.o0(SourceFile:139)
at z1.d0.a(SourceFile:119)
at v.g1.a(SourceFile:394)
at v.e1.d(SourceFile:32)
at z1.p.a(SourceFile:51)
at z1.f0.c(SourceFile:26)
at l2.p.K(SourceFile:59)
at c1.y.b(SourceFile:48)
at c1.z.c(SourceFile:162)
at z1.i1.a(SourceFile:1)
at z1.d0.o0(SourceFile:139)
at z1.d0.a(SourceFile:119)
at p.x.d(SourceFile:368)
at z1.p.a(SourceFile:51)
at p.z.a(SourceFile:11)
at p.z.o(SourceFile:28)
at x1.z.h(SourceFile:8)
at z1.p.a(SourceFile:83)
at p.v0.h(SourceFile:48)
at z1.p.a(SourceFile:83)
at k1.q0.h(SourceFile:1)
at z1.p.a(SourceFile:83)
at p.j.o(SourceFile:9)
at x1.z.h(SourceFile:8)
at z1.p.a(SourceFile:83)
at z1.f0.c(SourceFile:26)
at l2.p.K(SourceFile:59)
at c1.y.b(SourceFile:48)
at c1.z.c(SourceFile:162)
at z1.i1.a(SourceFile:1)
at z1.d0.o0(SourceFile:139)
at z1.d0.a(SourceFile:119)
at p.s.d(SourceFile:84)
at z1.p.a(SourceFile:51)
at p.z.a(SourceFile:88)
at p.z.o(SourceFile:15)
at x1.z.h(SourceFile:8)
at z1.p.a(SourceFile:83)
at z1.f0.c(SourceFile:26)
at l2.p.K(SourceFile:59)
at c1.y.b(SourceFile:48)
at c1.z.c(SourceFile:162)
at z1.i1.a(SourceFile:1)
at z1.d0.o0(SourceFile:139)
at z1.d0.a(SourceFile:119)
at z1.e0.a(SourceFile:34)
at v.t.d(SourceFile:83)
at z1.q.a(SourceFile:38)
at k1.q0.h(SourceFile:1)
at z1.v.a(SourceFile:11)
at v.f0.h(SourceFile:99)
at z1.v.a(SourceFile:11)
at q.k0.b(SourceFile:34)
at q.k0.c(SourceFile:52)
at l2.p.K(SourceFile:59)
at c1.y.b(SourceFile:48)
at c1.z.c(SourceFile:162)
at z1.i1.a(SourceFile:1)
at z1.e0.q0(SourceFile:107)
at z1.e0.a(SourceFile:106)
at x1.g1.d(SourceFile:84)
at z1.q.a(SourceFile:38)
at q.k0.b(SourceFile:34)
at q.k0.c(SourceFile:52)
at l2.p.K(SourceFile:59)
at c1.y.b(SourceFile:48)
at c1.z.c(SourceFile:162)
at z1.i1.a(SourceFile:1)
at z1.e0.q0(SourceFile:107)
at z1.l0.c(SourceFile:18)
at z1.l0.l(SourceFile:1)
at z1.l0.i(SourceFile:57)
at androidx.compose.ui.platform.AndroidComposeView.onMeasure(SourceFile:79)
at android.view.View.measure(View.java:27129)
at androidx.compose.ui.platform.a.g(SourceFile:1)
at androidx.compose.ui.platform.a.onMeasure(Unknown Source:3)
at android.view.View.measure(View.java:27129)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7980)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:197)
at androidx.appcompat.widget.ContentFrameLayout.onMeasure(Unknown Source:159)
at android.view.View.measure(View.java:27129)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7980)
at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
at android.view.View.measure(View.java:27129)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7980)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:197)
at android.view.View.measure(View.java:27129)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7980)
at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
at android.view.View.measure(View.java:27129)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7980)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:197)
at com.android.internal.policy.DecorView.onMeasure(DecorView.java:1278)
at android.view.View.measure(View.java:27129)
at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4541)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3972)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2924)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10513)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1108)
at android.view.Choreographer.doCallbacks(Choreographer.java:866)
at android.view.Choreographer.doFrame(Choreographer.java:797)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:226)
at android.os.Looper.loop(Looper.java:313)
at android.app.ActivityThread.main(ActivityThread.java:8751)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

**Comment by T8RIN** [comment]
maybe fixed
