### ISSUE TITLE
Crash due to failed image stitching

### ISSUE THREAD

**Issue by jcperil** [T8RIN/ImageToolbox#554]
#### Steps to reproduce:

1. Select **Image Stitching** and choose 5 images. It shows **Loading...**
2. Tap on the lock button twice, i.e. unlock and lock again.
3. App crashes. 100% reproducible.

<p align="center"><img src="https://github.com/T8RIN/ImageToolbox/assets/89805719/5fd7eecf-ad5e-4b83-9f6c-d6c552bcb55c" height="200px" /></p>

<details><summary><b>Crash log </b></summary><p>

```
[Bug] App Crash: IndexOutOfBoundsException

Device: M2101K6P (Redmi - sweetin), SDK: 33 (13), App: 2.4.3-alpha02 (99)

java.lang.IndexOutOfBoundsException: Index 2, size 2
	at y.z0.b(SourceFile:31)
	at y.z0.c(SourceFile:1)
	at n0.d.g1(SourceFile:5)
	at w.o.b(SourceFile:1)
	at w.u.a(SourceFile:7)
	at w.v.o(SourceFile:1262)
	at s.w0.o(SourceFile:371)
	at x1.f0.d(SourceFile:74)
	at z1.p.a(SourceFile:51)
	at r.m.g(SourceFile:44)
	at r.m.n(SourceFile:476)
	at x1.z.h(SourceFile:8)
	at z1.p.a(SourceFile:83)
	at r.m.g(SourceFile:10)
	at r.m.n(SourceFile:489)
	at x1.z.h(SourceFile:8)
	at z1.p.a(SourceFile:83)
	at k1.r0.h(SourceFile:1)
	at z1.p.a(SourceFile:83)
	at k1.r0.h(SourceFile:1)
	at z1.p.a(SourceFile:83)
	at z1.f0.c(SourceFile:26)
	at l5.l.B(SourceFile:59)
	at c1.x.b(SourceFile:48)
	at c1.y.c(SourceFile:162)
	at z1.j1.a(SourceFile:1)
	at z1.d0.o0(SourceFile:139)
	at z1.l0.b(SourceFile:44)
	at z1.l0.j(SourceFile:139)
	at z1.l0.g(SourceFile:67)
	at androidx.compose.ui.platform.AndroidComposeView.w(SourceFile:32)
	at z1.e1.a(SourceFile:4)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(SourceFile:14)
	at android.view.View.draw(View.java:23356)
	at android.view.View.updateDisplayListIfDirty(View.java:22210)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4528)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4501)
	at android.view.View.updateDisplayListIfDirty(View.java:22160)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4528)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4501)
	at android.view.View.updateDisplayListIfDirty(View.java:22160)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4528)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4501)
	at android.view.View.updateDisplayListIfDirty(View.java:22160)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4528)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4501)
	at android.view.View.updateDisplayListIfDirty(View.java:22160)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4528)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4501)
	at android.view.View.updateDisplayListIfDirty(View.java:22160)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4528)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4501)
	at android.view.View.updateDisplayListIfDirty(View.java:22160)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:682)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:690)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:795)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4924)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4625)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3813)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2543)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9465)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1451)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1459)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1089)
	at android.view.Choreographer.doFrame(Choreographer.java:1003)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1431)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8296)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
```
</details>

**Comment by T8RIN** [comment]
Check #530
