### ISSUE TITLE
[Bug] App Crash: IllegalArgumentException

### ISSUE THREAD

**Issue by J43git** [T8RIN/ImageToolbox#580]
The scrolling down various color palettes bug is still present. I tried deleting palettes to see if that fixes the issue but I've got nothing so far.

I even cleared the data and still got nothing.

**Comment by T8RIN** [comment]
> The scrolling down various color palettes bug is still present. I tried deleting palettes to see if that fixes the issue but I've got nothing so far.
> 
> I even cleared the data and still got nothing. 

Hm? Can you record a video and send full stack trace please?

**Comment by T8RIN** [comment]
It's seems to be an Library bug, again :/

**Comment by T8RIN** [comment]
It looks like Lookahead measuring bug in compose 👎

**Comment by T8RIN** [comment]
Well, if i drop release now, then many people will encounter this, at least a fixed a lot more, waiting two weeks for the fix, if they do that

**Comment by J43git** [comment]
[Bug] App Crash: IllegalArgumentException

Device: moto e (motorola - ginna), SDK: 29 (10), App: 2.5.0-rc02 (103)

java.lang.IllegalArgumentException: Lookahead pass was never done for target content.
	at o.t.b(SourceFile:99)
	at z1.s.a(SourceFile:38)
	at o.a0.a(SourceFile:88)
	at o.a0.i(SourceFile:15)
	at x1.x.h(SourceFile:8)
	at z1.x.a(SourceFile:11)
	at p.k0.b(SourceFile:23)
	at p.k0.c(SourceFile:13)
	at i7.j9.i(SourceFile:59)
	at c1.z.b(SourceFile:48)
	at c1.a0.c(SourceFile:162)
	at z1.m1.a(SourceFile:1)
	at z1.g0.q0(SourceFile:114)
	at androidx.compose.ui.node.a.K(SourceFile:17)
	at androidx.compose.ui.node.a.L(SourceFile:18)
	at z1.g0.o(SourceFile:46)
	at z1.g0.o0(SourceFile:131)
	at z1.s.Z(SourceFile:18)
	at x1.c1.j(SourceFile:29)
	at x1.c1.k(SourceFile:1)
	at q.s.f(SourceFile:382)
	at q.s.o(SourceFile:1506)
	at z1.k0.k(SourceFile:7)
	at z1.x.Z(SourceFile:16)
	at x1.c1.g(SourceFile:68)
	at a.h.k(SourceFile:75)
	at a.h.o(SourceFile:1184)
	at z1.k0.k(SourceFile:7)
	at z1.x.Z(SourceFile:16)
	at x1.c1.g(SourceFile:68)
	at u.n.a(SourceFile:178)
	at u.n.o(SourceFile:101)
	at z1.k0.k(SourceFile:7)
	at z1.x.Z(SourceFile:16)
	at x1.c1.e(SourceFile:26)
	at q.y0.a(SourceFile:202)
	at q.y0.c(SourceFile:203)
	at i7.j9.i(SourceFile:59)
	at c1.z.b(SourceFile:48)
	at c1.a0.c(SourceFile:162)
	at z1.m1.a(SourceFile:1)
	at z1.g0.p0(SourceFile:95)
	at z1.g0.Z(SourceFile:90)
	at x1.c1.e(SourceFile:26)
	at u.s.b(SourceFile:45)
	at u.t.a(SourceFile:36)
	at u.t.o(SourceFile:23)
	at z1.k0.k(SourceFile:7)
	at p.k0.b(SourceFile:91)
	at p.k0.c(SourceFile:17)
	at i7.j9.i(SourceFile:59)
	at c1.z.b(SourceFile:48)
	at c1.a0.c(SourceFile:162)
	at z1.m1.a(SourceFile:1)
	at z1.g0.o(SourceFile:100)
	at z1.g0.o0(SourceFile:131)
	at z1.s.Z(SourceFile:18)
	at x1.c1.j(SourceFile:29)
	at x1.c1.k(SourceFile:1)
	at q.s.f(SourceFile:382)
	at q.s.o(SourceFile:1506)
	at z1.k0.k(SourceFile:7)
	at z1.x.Z(SourceFile:16)
	at x1.c1.j(SourceFile:29)
	at x1.c1.k(SourceFile:1)
	at q.s.f(SourceFile:382)
	at q.s.o(SourceFile:1506)
	at z1.k0.k(SourceFile:7)
	at z1.x.Z(SourceFile:16)
	at x1.c1.g(SourceFile:68)
	at a.h.k(SourceFile:75)
	at a.h.o(SourceFile:1184)
	at z1.k0.k(SourceFile:7)
	at z1.x.Z(SourceFile:16)
	at x1.c1.j(SourceFile:29)
	at x1.c1.k(SourceFile:1)
	at q.s.f(SourceFile:382)
	at q.s.o(SourceFile:1506)
	at z1.k0.k(SourceFile:7)
	at z1.x.Z(SourceFile:16)
	at x1.c1.j(SourceFile:29)
	at x1.c1.k(SourceFile:1)
	at q.s.f(SourceFile:27)
	at q.s.o(SourceFile:1514)
	at z1.k0.k(SourceFile:7)
	at z1.x.Z(SourceFile:16)
	at x1.c1.g(SourceFile:68)
	at u.n.a(SourceFile:182)
	at u.n.o(SourceFile:107)
	at z1.k0.k(SourceFile:7)
	at z1.x.Z(SourceFile:16)
	at q.y0.a(SourceFile:241)
	at q.y0.c(SourceFile:203)
	at i7.j9.i(SourceFile:59)
	at c1.z.b(SourceFile:48)
	at c1.a0.c(SourceFile:162)
	at z1.m1.a(SourceFile:1)
	at z1.g0.p0(SourceFile:95)
	at z1.g0.Z(SourceFile:90)
	at x1.c1.l(SourceFile:37)
	at w.b0.f(SourceFile:592)
	at w.b0.o(SourceFile:265)
	at x1.a0.k(SourceFile:25)
	at w.c0.k(SourceFile:1)
	at x1.c0.k(SourceFile:43)
	at p.k0.b(SourceFile:91)
	at p.k0.c(SourceFile:17)
	at i7.j9.i(SourceFile:59)
	at c1.z.b(SourceFile:48)
	at c1.a0.c(SourceFile:162)
	at z1.m1.a(SourceFile:1)
	at z1.g0.o(SourceFile:100)
	at z1.g0.o0(SourceFile:131)
	at z1.s.Z(SourceFile:18)
	at x1.c1.j(SourceFile:29)
	at x1.c1.k(SourceFile:1)
	at q.s.f(SourceFile:382)
	at q.s.o(SourceFile:1506)
	at z1.k0.k(SourceFile:7)
	at z1.x.Z(SourceFile:16)
	at x1.c1.e(SourceFile:26)
	at q.y0.a(SourceFile:202)
	at q.y0.c(SourceFile:203)
	at i7.j9.i(SourceFile:59)
	at c1.z.b(SourceFile:48)
	at c1.a0.c(SourceFile:162)
	at z1.m1.a(SourceFile:1)
	at z1.g0.p0(SourceFile:95)
	at androidx.compose.ui.node.a.O(SourceFile:32)
	at z1.o0.i(SourceFile:97)
	at androidx.compose.ui.platform.AndroidComposeView.v(SourceFile:8)
	at androidx.compose.ui.node.a.j(SourceFile:41)
	at m.x.a(SourceFile:627)
	at m.x.o(SourceFile:163)
	at r.z.a(SourceFile:17)
	at q.a3.o(SourceFile:310)
	at q.k.c(SourceFile:387)
	at r.y2.a(SourceFile:46)
	at r.z1.b(SourceFile:1)
	at r.h.w(SourceFile:118)
	at r.h.m(SourceFile:13)
	at r.f1.w(SourceFile:39)
	at r.f1.m(SourceFile:13)
	at r.y1.w(SourceFile:37)
	at r.y1.m(SourceFile:13)
	at r.x.w(SourceFile:42)
	at r.x.m(SourceFile:13)
	at q.f2.w(SourceFile:197)
	at q.f2.m(SourceFile:13)
	at i7.r5.P(SourceFile:5)
	at h7.k6.q(SourceFile:1)
	at q.g2.a(SourceFile:1)
	at r.y.w(SourceFile:43)
	at r.y.m(SourceFile:13)
	at i7.r5.P(SourceFile:5)
	at h7.k6.q(SourceFile:1)
	at r.a0.d(SourceFile:1)
	at w.p0.d(SourceFile:1)
	at r.z1.a(SourceFile:11)
	at r.i.w(SourceFile:193)
	at vb.a.j(SourceFile:1)
	at rc.e0.run(SourceFile:1)
	at androidx.compose.ui.platform.a1.R(SourceFile:7)
	at androidx.compose.ui.platform.z0.doFrame(SourceFile:10)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:964)
	at android.view.Choreographer.doCallbacks(Choreographer.java:790)
	at android.view.Choreographer.doFrame(Choreographer.java:721)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:241)
	at android.app.ActivityThread.main(ActivityThread.java:7604)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
	Suppressed: wc.f: [androidx.compose.ui.platform.b2@43e8a4, s0.g@a4360d, p1{Cancelling}@97129c2, a1@df413d3]
