### ISSUE TITLE
Crash scrolling the Create tab

### ISSUE THREAD

**Issue by uli-on** [T8RIN/ImageToolbox#593]
This crash happens only on the Create tab AND when you have previously scrolled through one of the two other tabs. 
EDIT: There seems to be a third dependency: Seems like the German language (app language) is a third prerequisite. 
EDIT 2: In French language it also happened on the Tools tab. 

```
[Bug] App Crash: IllegalArgumentException

Device: FP3 (Fairphone - FP3), SDK: 29 (10), App: 2.5.0 (104)

java.lang.IllegalArgumentException: Lookahead pass was never done for target content.
	at p.u.d(SourceFile:99)
	at a2.s.a(SourceFile:38)
	at p.b0.a(SourceFile:88)
	at p.b0.o(SourceFile:15)
	at y1.x.d(SourceFile:8)
	at a2.x.a(SourceFile:11)
	at q.k0.b(SourceFile:35)
	at q.k0.d(SourceFile:17)
	at m2.r.W(SourceFile:59)
	at d1.z.b(SourceFile:48)
	at d1.a0.c(SourceFile:162)
	at a2.m1.a(SourceFile:1)
	at a2.g0.q0(SourceFile:114)
	at androidx.compose.ui.node.a.J(SourceFile:17)
	at androidx.compose.ui.node.a.K(SourceFile:18)
	at a2.o0.c(SourceFile:8)
	at a2.o0.k(SourceFile:134)
	at a2.o0.e(SourceFile:99)
	at a2.o0.e(SourceFile:111)
	at a2.o0.e(SourceFile:111)
	at a2.o0.d(SourceFile:36)
	at a2.g0.q0(SourceFile:59)
	at a2.g0.a(SourceFile:101)
	at v.v.d(SourceFile:83)
	at a2.s.a(SourceFile:38)
	at l1.q0.d(SourceFile:1)
	at a2.x.a(SourceFile:11)
	at l1.q0.d(SourceFile:1)
	at a2.x.a(SourceFile:11)
	at l1.q0.d(SourceFile:1)
	at a2.x.a(SourceFile:11)
	at v.g0.d(SourceFile:99)
	at a2.x.a(SourceFile:11)
	at v.n1.d(SourceFile:117)
	at a2.x.a(SourceFile:11)
	at q.k0.b(SourceFile:35)
	at q.k0.d(SourceFile:17)
	at m2.r.W(SourceFile:59)
	at d1.z.b(SourceFile:48)
	at d1.a0.c(SourceFile:162)
	at a2.m1.a(SourceFile:1)
	at a2.g0.q0(SourceFile:114)
	at a2.g0.a(SourceFile:101)
	at y.k0.a(SourceFile:1)
	at z.r.a(SourceFile:82)
	at f8.j.T0(SourceFile:72)
	at z.t.p(SourceFile:516)
	at s.w0.f(SourceFile:59)
	at s.w0.p(SourceFile:350)
	at y1.d0.d(SourceFile:49)
	at a2.s.a(SourceFile:38)
	at l1.q0.d(SourceFile:1)
	at a2.x.a(SourceFile:11)
	at v.g0.d(SourceFile:99)
	at a2.x.a(SourceFile:11)
	at q.k0.b(SourceFile:35)
	at q.k0.d(SourceFile:17)
	at m2.r.W(SourceFile:59)
	at d1.z.b(SourceFile:48)
	at d1.a0.c(SourceFile:162)
	at a2.m1.a(SourceFile:1)
	at a2.g0.q0(SourceFile:114)
	at a2.g0.a(SourceFile:101)
	at p.z.d(SourceFile:369)
	at a2.s.a(SourceFile:38)
	at p.b0.a(SourceFile:11)
	at p.b0.o(SourceFile:28)
	at y1.x.d(SourceFile:8)
	at a2.x.a(SourceFile:11)
	at p.y0.d(SourceFile:218)
	at a2.x.a(SourceFile:11)
	at l1.q0.d(SourceFile:1)
	at a2.x.a(SourceFile:11)
	at p.k.o(SourceFile:9)
	at y1.x.d(SourceFile:8)
	at a2.x.a(SourceFile:11)
	at q.k0.b(SourceFile:35)
	at q.k0.d(SourceFile:17)
	at m2.r.W(SourceFile:59)
	at d1.z.b(SourceFile:48)
	at d1.a0.c(SourceFile:162)
	at a2.m1.a(SourceFile:1)
	at a2.g0.q0(SourceFile:114)
	at a2.g0.a(SourceFile:101)
	at p.u.d(SourceFile:84)
	at a2.s.a(SourceFile:38)
	at p.b0.a(SourceFile:88)
	at p.b0.o(SourceFile:15)
	at y1.x.d(SourceFile:8)
	at a2.x.a(SourceFile:11)
	at q.k0.b(SourceFile:35)
	at q.k0.d(SourceFile:17)
	at m2.r.W(SourceFile:59)
	at d1.z.b(SourceFile:48)
	at d1.a0.c(SourceFile:162)
	at a2.m1.a(SourceFile:1)
	at a2.g0.q0(SourceFile:114)
	at a2.g0.a(SourceFile:101)
	at v.i1.a(SourceFile:111)
	at v.h1.d(SourceFile:32)
	at a2.s.a(SourceFile:38)
	at q.k0.b(SourceFile:35)
	at q.k0.d(SourceFile:17)
	at m2.r.W(SourceFile:59)
	at d1.z.b(SourceFile:48)
	at d1.a0.c(SourceFile:162)
	at a2.m1.a(SourceFile:1)
	at a2.g0.q0(SourceFile:114)
	at a2.g0.a(SourceFile:101)
	at v.i1.a(SourceFile:389)
	at v.h1.d(SourceFile:32)
	at a2.s.a(SourceFile:38)
	at v.g0.d(SourceFile:99)
	at a2.x.a(SourceFile:11)
	at q.k0.b(SourceFile:35)
	at q.k0.d(SourceFile:17)
	at m2.r.W(SourceFile:59)
	at d1.z.b(SourceFile:48)
	at d1.a0.c(SourceFile:162)
	at a2.m1.a(SourceFile:1)
	at a2.g0.q0(SourceFile:114)
	at androidx.compose.ui.node.a.J(SourceFile:17)
	at androidx.compose.ui.node.a.K(SourceFile:18)
	at a2.o0.c(SourceFile:8)
	at a2.o0.k(SourceFile:134)
	at a2.o0.h(SourceFile:59)
	at androidx.compose.ui.platform.AndroidComposeView.v(SourceFile:32)
	at a2.h1.a(SourceFile:4)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(SourceFile:14)
	at android.view.View.draw(View.java:21982)
	at android.view.View.updateDisplayListIfDirty(View.java:20856)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4416)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4389)
	at android.view.View.updateDisplayListIfDirty(View.java:20816)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4416)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4389)
	at android.view.View.updateDisplayListIfDirty(View.java:20816)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4416)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4389)
	at android.view.View.updateDisplayListIfDirty(View.java:20816)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4416)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4389)
	at android.view.View.updateDisplayListIfDirty(View.java:20816)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4416)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4389)
	at android.view.View.updateDisplayListIfDirty(View.java:20816)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4416)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4389)
	at android.view.View.updateDisplayListIfDirty(View.java:20816)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:581)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:587)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:664)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3765)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3493)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2777)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1743)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7772)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1041)
	at android.view.Choreographer.doCallbacks(Choreographer.java:864)
	at android.view.Choreographer.doFrame(Choreographer.java:798)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1026)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7397)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

```

**Comment by uli-on** [comment]
Please, can you tell something about what we can do to avoid the crashes? Update what, downgrade the app to which version? Thank you!

**Comment by T8RIN** [comment]
No jetpack compose lib

**Comment by uli-on** [comment]
I'm afraid I don't have the user privs to update that one as I can't even find it in the file system.

**Comment by T8RIN** [comment]
Because that's compiled Library, how can you change it?

**Comment by T8RIN** [comment]
It's not a gms, check jetpack compose

**Comment by uli-on** [comment]
Thanks, Malik. I browsed portions of the page and am under the impression that I myself as a John Doe user can't really do anything but wait.

What's funny, though, is that I can scroll normally when I have set English as language from inside the app. Maybe you missed this second edit in the first post and it tells you something. I hope so.
