### ISSUE TITLE
[Bug] App Crash: ActivityNotFoundException when tapping Backup

### ISSUE THREAD

**Issue by Kevinf63** [T8RIN/ImageToolbox#801]
Device: Pixel 7 (google - panther), SDK: 34 (14), App: 2.6.1-alpha01 (118)android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.CREATE_DOCUMENT typ=*/* (has extras) }at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2250)at android.app.Instrumentation.execStartActivity(Instrumentation.java:1884)at android.app.Activity.startActivityForResult(Activity.java:5661)at a.r.startActivityForResult(SourceFile:2)at a.o.b(SourceFile:165)at d.h.F2(SourceFile:37)at b.a.a(SourceFile:1)at b.m.F2(SourceFile:1)at bg.h.a(SourceFile:206)at bg.h.d(SourceFile:76)at hf.p.a(SourceFile:42)at hf.p.d(SourceFile:24)at s.n0.a(SourceFile:14)at s.n0.n(SourceFile:12)at t.q3.z(SourceFile:320)at ea.a.k(SourceFile:1)at rc.c.n1(SourceFile:1)at gd.g.q(SourceFile:100)at gd.g.F(SourceFile:33)at gd.g.k(SourceFile:17)at y1.p0.C0(SourceFile:51)at y1.p0.m0(SourceFile:1)at s.k.m0(SourceFile:117)at y1.i.f(SourceFile:157)at y1.i.f(SourceFile:136)at y1.i.f(SourceFile:136)at y1.i.f(SourceFile:136)at y1.i.f(SourceFile:136)at y1.i.f(SourceFile:136)at y1.i.f(SourceFile:136)at y1.e.b(SourceFile:30)at y1.y.a(SourceFile:122)at e2.a0.G(SourceFile:79)at e2.a0.m(SourceFile:214)at e2.a0.dispatchTouchEvent(SourceFile:76)at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3123)at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2804)at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3123)at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2804)at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3123)at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2804)at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3123)at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2804)at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3123)at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2804)at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3123)at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2804)at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:490)at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1904)at android.app.Activity.dispatchTouchEvent(Activity.java:4411)at g.f0.dispatchTouchEvent(SourceFile:3)at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:448)at android.view.View.dispatchPointerEvent(View.java:15928)at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:7242)at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7032)at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6435)at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6492)at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6458)at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6623)at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6466)at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6680)at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6439)at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6492)at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6458)at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6466)at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6439)at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9432)at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9383)at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9352)at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9558)at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:267)at android.os.MessageQueue.nativePollOnce(Native Method)at android.os.MessageQueue.next(MessageQueue.java:335)at android.os.Looper.loopOnce(Looper.java:162)at android.os.Looper.loop(Looper.java:294)at android.app.ActivityThread.main(ActivityThread.java:8279)at java.lang.reflect.Method.invoke(Native Method)at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)at com.android.internal.os.ExecInit.main(ExecInit.java:49)at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)Suppressed: ld.f: [e2.k2@f41b66c, v0.h@817c435, p1{Cancelling}@5e4e0ca, h1@52d723b]

**Comment by T8RIN** [comment]
You deleted the system file manager?

**Comment by T8RIN** [comment]
- Ofc, i added a message instead of a crash, but it won't work without system one (

**Comment by Kevinf63** [comment]
> * Ofc, i added a message instead of a crash, but it won't work without system one (

Thanks for providing clarity with that new commit 995cb9d. I've made sure it's visible!

**Comment by T8RIN** [comment]
Good :)
