### ISSUE TITLE
App Crash: IllegalArgumentException

### ISSUE THREAD

**Issue by aiyu-ayaan** [T8RIN/ImageToolbox#815]
[Bug] App Crash: IllegalArgumentException

Device: RMX3842 (realme - RE5C84L1), SDK: 34 (14), App: 2.6.1-beta02 (122)

java.lang.IllegalArgumentException: Can't represent a width of 1166400 and height of 486 in Constraints
	at ne.k.B(SourceFile:126)
	at i2.g.f(SourceFile:1)
	at w.p.b(SourceFile:213)
	at d2.d0.a(SourceFile:38)
	at d2.p0.b(SourceFile:32)
	at d2.p0.e(SourceFile:587)
	at g8.za.c(SourceFile:60)
	at f1.v.a(SourceFile:52)
	at f1.w.c(SourceFile:153)
	at d2.u1.a(SourceFile:1)
	at d2.n0.s0(SourceFile:112)
	at d2.n0.a(SourceFile:91)
	at w.w.e(SourceFile:114)
	at d2.x.a(SourceFile:49)
	at w.n1.b(SourceFile:33)
	at d2.d0.a(SourceFile:38)
	at w.n1.b(SourceFile:33)
	at d2.d0.a(SourceFile:38)
	at o1.t0.b(SourceFile:1)
	at d2.d0.a(SourceFile:38)
	at o1.n.b(SourceFile:1)
	at d2.d0.a(SourceFile:38)
	at d2.p0.b(SourceFile:32)
	at d2.p0.e(SourceFile:587)
	at g8.za.c(SourceFile:60)
	at f1.v.a(SourceFile:52)
	at f1.w.c(SourceFile:153)
	at d2.u1.a(SourceFile:1)
	at d2.n0.s0(SourceFile:112)
	at d2.n0.a(SourceFile:91)
	at w.w.e(SourceFile:114)
	at d2.x.a(SourceFile:49)
	at d2.p0.b(SourceFile:32)
	at d2.p0.e(SourceFile:587)
	at g8.za.c(SourceFile:60)
	at f1.v.a(SourceFile:52)
	at f1.w.c(SourceFile:153)
	at d2.u1.a(SourceFile:1)
	at d2.n0.s0(SourceFile:112)
	at d2.n0.a(SourceFile:91)
	at w.w.e(SourceFile:114)
	at d2.x.a(SourceFile:49)
	at d2.p0.b(SourceFile:32)
	at d2.p0.e(SourceFile:587)
	at g8.za.c(SourceFile:60)
	at f1.v.a(SourceFile:52)
	at f1.w.c(SourceFile:153)
	at d2.u1.a(SourceFile:1)
	at d2.n0.s0(SourceFile:112)
	at d2.n0.a(SourceFile:91)
	at o3.c.c(SourceFile:1)
	at q.z.e(SourceFile:27)
	at d2.x.a(SourceFile:49)
	at q.a1.b(SourceFile:222)
	at d2.d0.a(SourceFile:38)
	at o1.t0.b(SourceFile:1)
	at d2.d0.a(SourceFile:38)
	at q.h.h(SourceFile:126)
	at q.h.k(SourceFile:1060)
	at b2.e0.b(SourceFile:8)
	at d2.d0.a(SourceFile:38)
	at d2.p0.b(SourceFile:32)
	at d2.p0.e(SourceFile:587)
	at g8.za.c(SourceFile:60)
	at f1.v.a(SourceFile:52)
	at f1.w.c(SourceFile:153)
	at d2.u1.a(SourceFile:1)
	at d2.n0.s0(SourceFile:112)
	at d2.n0.a(SourceFile:91)
	at q.q.e(SourceFile:40)
	at d2.x.a(SourceFile:49)
	at q.w.b(SourceFile:1)
	at d2.d.b(SourceFile:1)
	at d2.d0.a(SourceFile:38)
	at w.h0.b(SourceFile:99)
	at d2.d0.a(SourceFile:38)
	at d2.p0.b(SourceFile:32)
	at d2.p0.e(SourceFile:587)
	at g8.za.c(SourceFile:60)
	at f1.v.a(SourceFile:52)
	at f1.w.c(SourceFile:153)
	at d2.u1.a(SourceFile:1)
	at d2.n0.s0(SourceFile:112)
	at androidx.compose.ui.node.a.K(SourceFile:17)
	at androidx.compose.ui.node.a.L(SourceFile:18)
	at d2.w0.c(SourceFile:8)
	at d2.w0.k(SourceFile:124)
	at d2.w0.h(SourceFile:78)
	at e2.a0.v(SourceFile:34)
	at d2.q1.a(SourceFile:4)
	at e2.a0.dispatchDraw(SourceFile:14)
	at android.view.View.draw(View.java:24212)
	at android.view.View.updateDisplayListIfDirty(View.java:23027)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4628)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4601)
	at android.view.View.updateDisplayListIfDirty(View.java:22978)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4628)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4601)
	at android.view.View.updateDisplayListIfDirty(View.java:22978)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4628)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4601)
	at android.view.View.updateDisplayListIfDirty(View.java:22978)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4628)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4601)
	at android.view.View.updateDisplayListIfDirty(View.java:22978)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4628)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4601)
	at android.view.View.updateDisplayListIfDirty(View.java:22978)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4628)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4601)
	at android.view.View.updateDisplayListIfDirty(View.java:22978)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:713)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:719)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:821)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:5490)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:5163)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4240)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2741)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10139)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1552)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1561)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1117)
	at android.view.Choreographer.doFrame(Choreographer.java:1002)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1535)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:257)
	at android.os.Looper.loop(Looper.java:368)
	at android.app.ActivityThread.main(ActivityThread.java:8825)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)

**Comment by T8RIN** [comment]
compose lib bug, i can't fix it :(
