### ISSUE TITLE
[Bug] App crash with `IllegalArgumentException` when using Color Filter.

### ISSUE THREAD

**Issue by cattokomo** [T8RIN/ImageToolbox#907]
**Steps to reproduce**
1. Open app
2. Single edit image 
3. Select image
4. Tap filter (icon) 
5. Select "Color Filter" and try out (Tap left icon). This will bring up a menu with preview of the message and the settings for the filter. 
6. Apply the filter 
7. Crash

**The error and the stacktrace**
```
Device: SM-A105G (samsung - a10), SDK: 30 (11), App: 2.6.1-alpha01 (118)

java.lang.IllegalArgumentException: Callable expects 2 arguments, but 1 were provided.
	at ca.h.r0(SourceFile:42)
	at xa.j.c(SourceFile:13)
	at wa.s.b(SourceFile:439)
	at ru.tech.imageresizershrinker.core.filters.presentation.model.UiFilter.a(SourceFile:94)
	at mh.b.n(SourceFile:135)
	at r.s0.a(SourceFile:508)
	at r.s0.d(SourceFile:137)
	at hf.p.a(SourceFile:90)
	at hf.p.d(SourceFile:52)
	at o.d0.n(SourceFile:275)
	at t.c3.z(SourceFile:134)
	at ea.a.k(SourceFile:1)
	at rc.c.n1(SourceFile:1)
	at gd.g.q(SourceFile:100)
	at gd.g.F(SourceFile:33)
	at gd.g.k(SourceFile:17)
	at y1.p0.C0(SourceFile:51)
	at y1.p0.m0(SourceFile:1)
	at s.k.m0(SourceFile:117)
	at y1.i.f(SourceFile:157)
	at y1.i.f(SourceFile:136)
	at y1.i.f(SourceFile:136)
	at y1.e.b(SourceFile:30)
	at y1.y.a(SourceFile:122)
	at e2.a0.G(SourceFile:79)
	at e2.a0.m(SourceFile:214)
	at e2.a0.dispatchTouchEvent(SourceFile:76)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:913)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1957)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4182)
	at g.f0.dispatchTouchEvent(SourceFile:3)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:871)
	at android.view.View.dispatchPointerEvent(View.java:15458)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:7457)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7233)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6595)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6652)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6618)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6786)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6626)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6843)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6599)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6652)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6618)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6626)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6599)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9880)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9718)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9671)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:10014)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:220)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loop(Looper.java:206)
	at android.app.ActivityThread.main(ActivityThread.java:8645)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
	Suppressed: ld.f: [e2.k2@267cb34, v0.h@4538d5d, p1{Cancelling}@f93b6d2, h1@c0503a3]
```

**Comment by T8RIN** [comment]
You are using old alpha 👀 there are stable 2.7.0 and a bunch of 2.7.1 alphas released
