### ISSUE TITLE
Can't use OCR 

### ISSUE THREAD

**Issue by xyzippy** [T8RIN/ImageToolbox#916]
Cannot use OCR

To Reproduce:
Use OCR, pick image

Expected behavior:The app will show an error message

 - Device: Redmi 10C
 - OS: MIUI 14 Android 13

![Screenshot_2024-03-24-08-12-17-395_ru tech imageresizershrinker](https://github.com/T8RIN/ImageToolbox/assets/159468466/00f8ba71-9c63-4c57-9ce1-cc518efdda7a)

[Bug] App Crash: RuntimeException

Device: 220333QAG (Redmi - fog), SDK: 33 (13), App: 2.7.1-beta01 (128)

java.lang.RuntimeException: Failed to read bitmap
	at com.googlecode.tesseract.android.TessBaseAPI.d(SourceFile:36)
	at A9.e.x(SourceFile:136)
	at L4.a.k(SourceFile:9)
	at o6.H.run(SourceFile:97)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: t6.g: [s0{Cancelling}@91cd9d9, Dispatchers.Main.immediate]

**Comment by T8RIN** [comment]
Thanks for finding

**Comment by T8RIN** [comment]
Fixed
